/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReputationRouteImport } from './routes/reputation'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortraitsRouteImport } from './routes/portraits'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReputationAgentIdRouteImport } from './routes/reputation_.$agentId'
import { Route as PortraitsAgentIdRouteImport } from './routes/portraits_.$agentId'

const ReputationRoute = ReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortraitsRoute = PortraitsRouteImport.update({
  id: '/portraits',
  path: '/portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReputationAgentIdRoute = ReputationAgentIdRouteImport.update({
  id: '/reputation_/$agentId',
  path: '/reputation/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortraitsAgentIdRoute = PortraitsAgentIdRouteImport.update({
  id: '/portraits_/$agentId',
  path: '/portraits/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/developers': typeof DevelopersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portraits': typeof PortraitsRoute
  '/pricing': typeof PricingRoute
  '/reputation': typeof ReputationRoute
  '/portraits/$agentId': typeof PortraitsAgentIdRoute
  '/reputation/$agentId': typeof ReputationAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/developers': typeof DevelopersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portraits': typeof PortraitsRoute
  '/pricing': typeof PricingRoute
  '/reputation': typeof ReputationRoute
  '/portraits/$agentId': typeof PortraitsAgentIdRoute
  '/reputation/$agentId': typeof ReputationAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/developers': typeof DevelopersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portraits': typeof PortraitsRoute
  '/pricing': typeof PricingRoute
  '/reputation': typeof ReputationRoute
  '/portraits_/$agentId': typeof PortraitsAgentIdRoute
  '/reputation_/$agentId': typeof ReputationAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/developers'
    | '/how-it-works'
    | '/portraits'
    | '/pricing'
    | '/reputation'
    | '/portraits/$agentId'
    | '/reputation/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/developers'
    | '/how-it-works'
    | '/portraits'
    | '/pricing'
    | '/reputation'
    | '/portraits/$agentId'
    | '/reputation/$agentId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/developers'
    | '/how-it-works'
    | '/portraits'
    | '/pricing'
    | '/reputation'
    | '/portraits_/$agentId'
    | '/reputation_/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  DevelopersRoute: typeof DevelopersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PortraitsRoute: typeof PortraitsRoute
  PricingRoute: typeof PricingRoute
  ReputationRoute: typeof ReputationRoute
  PortraitsAgentIdRoute: typeof PortraitsAgentIdRoute
  ReputationAgentIdRoute: typeof ReputationAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reputation': {
      id: '/reputation'
      path: '/reputation'
      fullPath: '/reputation'
      preLoaderRoute: typeof ReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portraits': {
      id: '/portraits'
      path: '/portraits'
      fullPath: '/portraits'
      preLoaderRoute: typeof PortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reputation_/$agentId': {
      id: '/reputation_/$agentId'
      path: '/reputation/$agentId'
      fullPath: '/reputation/$agentId'
      preLoaderRoute: typeof ReputationAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portraits_/$agentId': {
      id: '/portraits_/$agentId'
      path: '/portraits/$agentId'
      fullPath: '/portraits/$agentId'
      preLoaderRoute: typeof PortraitsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  DevelopersRoute: DevelopersRoute,
  HowItWorksRoute: HowItWorksRoute,
  PortraitsRoute: PortraitsRoute,
  PricingRoute: PricingRoute,
  ReputationRoute: ReputationRoute,
  PortraitsAgentIdRoute: PortraitsAgentIdRoute,
  ReputationAgentIdRoute: ReputationAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
